#pragma once

#define PF_DEEP_COLOR_AWARE 1

#include "AEConfig.h"
#include "entry.h"
#include "AE_Effect.h"
#include "AE_EffectUI.h"
#include "AE_EffectCB.h"
#include "AE_Macros.h"
#include "Param_Utils.h"

constexpr A_long kMajorVersion = 0;
constexpr A_long kMinorVersion = 16;
constexpr A_long kBugVersion = 0;
constexpr A_long kBuildVersion = 1;
constexpr PF_ParamIndex kSurfaceAnimationPropertyCount = 84;
constexpr PF_ParamIndex kSurfaceAnimationBankStride =
    kSurfaceAnimationPropertyCount + 2;
constexpr PF_ParamIndex kAdditionalSurfaceAnimationBanks = 7;

enum ParamIndex {
    kParamInput = 0,
    kParamTessellation,
    kParamWireframe,
    kParamPoint00,
    kParamPoint01,
    kParamPoint02,
    kParamPoint03,
    kParamPoint10,
    kParamPoint11,
    kParamPoint12,
    kParamPoint13,
    kParamPoint20,
    kParamPoint21,
    kParamPoint22,
    kParamPoint23,
    kParamPoint30,
    kParamPoint31,
    kParamPoint32,
    kParamPoint33,
    kParamPerspective,
    kParamCameraDistance,
    kParamRotationX,
    kParamRotationY,
    kParamRotationZ,
    kParamDepth00,
    kParamDepth01,
    kParamDepth02,
    kParamDepth03,
    kParamDepth10,
    kParamDepth11,
    kParamDepth12,
    kParamDepth13,
    kParamDepth20,
    kParamDepth21,
    kParamDepth22,
    kParamDepth23,
    kParamDepth30,
    kParamDepth31,
    kParamDepth32,
    kParamDepth33,
    kParamSceneData,
    kParamSurfacesStart,
    kParamSurfaceCount,
    kParamSurfaceSelect,
    kParamAddSurface,
    kParamDuplicateSurface,
    kParamDeleteSurface,
    kParamSurfaceSizeX,
    kParamSurfaceSizeY,
    kParamSurfacePosition,
    kParamSurfaceRotationOriginStart,
    kParamSurfaceRotationOriginMode,
    kParamSurfaceRotationOriginX,
    kParamSurfaceRotationOriginY,
    kParamSurfaceRotationOriginEnd,
    kParamSurfaceScaleStart,
    kParamSurfaceScaleX,
    kParamSurfaceScaleY,
    kParamSurfaceScaleZ,
    kParamSurfaceScaleEnd,
    kParamSurfaceDivisionsStart,
    kParamSurfaceDivisionsX,
    kParamSurfaceDivisionsY,
    kParamSurfaceDivisionsEnd,
    kParamSurfaceThickness,
    kParamSurfaceDeformStart,
    kParamSurfaceBendX,
    kParamSurfaceBendY,
    kParamSurfaceRollEdge,
    kParamSurfaceRollAngle,
    kParamSurfaceRollLength,
    kParamSurfaceCornerCurlStart,
    kParamSurfaceCornerSelect,
    kParamSurfaceCornerAmount,
    kParamSurfaceCornerRadius,
    kParamSurfaceCornerDirection,
    kParamSurfaceCornerLength,
    kParamSurfaceCorner2Amount,
    kParamSurfaceCorner2Radius,
    kParamSurfaceCorner2Direction,
    kParamSurfaceCorner2Length,
    kParamSurfaceCorner3Amount,
    kParamSurfaceCorner3Radius,
    kParamSurfaceCorner3Direction,
    kParamSurfaceCorner3Length,
    kParamSurfaceCorner4Amount,
    kParamSurfaceCorner4Radius,
    kParamSurfaceCorner4Direction,
    kParamSurfaceCorner4Length,
    kParamSurfaceCornerCurlEnd,
    kParamSurfaceEdgeTwistStart,
    kParamSurfaceTwistEdge,
    kParamSurfaceTwistAngle,
    kParamSurfaceTwistFalloff,
    kParamSurfaceTwist2Angle,
    kParamSurfaceTwist2Falloff,
    kParamSurfaceTwist3Angle,
    kParamSurfaceTwist3Falloff,
    kParamSurfaceTwist4Angle,
    kParamSurfaceTwist4Falloff,
    kParamSurfaceEdgeTwistEnd,
    kParamSurfaceDeformEnd,
    kParamSurfaceMaterialStart,
    kParamSurfaceSourceSlot,
    kParamSurfaceBackSourceSlot,
    kParamSurfaceSourceLayersStart,
    kParamSurfaceSourceLayer1,
    kParamSurfaceSourceLayer2,
    kParamSurfaceSourceLayer3,
    kParamSurfaceSourceLayer4,
    kParamSurfaceSourceLayer5,
    kParamSurfaceSourceLayer6,
    kParamSurfaceSourceLayer7,
    kParamSurfaceSourceLayer8,
    kParamSurfaceSourceLayersEnd,
    kParamSurfaceImageSize,
    kParamSurfaceImageBorder,
    kParamSurfaceOpacity,
    kParamSurfaceDiffuse,
    kParamSurfaceSpecular,
    kParamSurfaceShininess,
    kParamSurfaceMaterialEnd,
    kParamSurfaceAnimationBanksStart,
    kParamSurfacesEnd =
        kParamSurfaceAnimationBanksStart +
        kAdditionalSurfaceAnimationBanks * kSurfaceAnimationBankStride,
    kParamCameraStart,
    kParamCameraOffsetX,
    kParamCameraOffsetY,
    kParamCameraOffsetZ,
    kParamCameraRotationX,
    kParamCameraRotationY,
    kParamCameraRotationZ,
    kParamCameraEnd,
    kParamLightsStart,
    kParamLightingEnabled,
    kParamLightRotationX,
    kParamLightRotationY,
    kParamLightIntensity,
    kParamAmbientLight,
    kParamLightsEnd,
    kParamRenderSettingsStart,
    kParamTextureFilter,
    kParamBackfaceCulling,
    kParamOutputBoundsMode,
    kParamOutputPaddingX,
    kParamOutputPaddingY,
    kParamRenderSettingsEnd,
    kParamCount
};

enum ParamDiskId {
    kDiskTessellation = 1,
    kDiskWireframe,
    kDiskPerspective,
    kDiskCameraDistance,
    kDiskRotationX,
    kDiskRotationY,
    kDiskRotationZ,
    kDiskPoint00 = 100,
    kDiskDepth00 = 200,
    kDiskSceneData = 300,
    kDiskSurfacesStart,
    kDiskSurfaceCount,
    kDiskSurfaceSelect,
    kDiskAddSurface,
    kDiskDuplicateSurface,
    kDiskDeleteSurface,
    kDiskSurfacesEnd,
    kDiskSurfaceSizeX,
    kDiskSurfaceSizeY,
    kDiskSurfacePosition,
    kDiskSurfaceScaleStart,
    kDiskSurfaceScaleX,
    kDiskSurfaceScaleY,
    kDiskSurfaceScaleZ,
    kDiskSurfaceScaleEnd,
    kDiskSurfaceDivisionsStart,
    kDiskSurfaceDivisionsX,
    kDiskSurfaceDivisionsY,
    kDiskSurfaceDivisionsEnd,
    kDiskSurfaceMaterialStart,
    kDiskSurfaceSourceSlot,
    kDiskSurfaceSourceLayersStart,
    kDiskSurfaceSourceLayer1,
    kDiskSurfaceSourceLayer2,
    kDiskSurfaceSourceLayer3,
    kDiskSurfaceSourceLayer4,
    kDiskSurfaceSourceLayer5,
    kDiskSurfaceSourceLayer6,
    kDiskSurfaceSourceLayer7,
    kDiskSurfaceSourceLayer8,
    kDiskSurfaceSourceLayersEnd,
    kDiskSurfaceImageSize,
    kDiskSurfaceImageBorder,
    kDiskSurfaceOpacity,
    kDiskSurfaceMaterialEnd,
    kDiskSurfaceThickness,
    kDiskSurfaceDiffuse,
    kDiskSurfaceSpecular,
    kDiskSurfaceShininess,
    kDiskCameraStart,
    kDiskCameraOffsetX,
    kDiskCameraOffsetY,
    kDiskCameraOffsetZ,
    kDiskCameraRotationX,
    kDiskCameraRotationY,
    kDiskCameraRotationZ,
    kDiskCameraEnd,
    kDiskLightsStart,
    kDiskLightingEnabled,
    kDiskLightRotationX,
    kDiskLightRotationY,
    kDiskLightIntensity,
    kDiskAmbientLight,
    kDiskLightsEnd,
    kDiskRenderSettingsStart,
    kDiskTextureFilter,
    kDiskBackfaceCulling,
    kDiskRenderSettingsEnd,
    kDiskSurfaceDeformStart,
    kDiskSurfaceBendX,
    kDiskSurfaceBendY,
    kDiskSurfaceRollEdge,
    kDiskSurfaceRollAngle,
    kDiskSurfaceRollLength,
    kDiskSurfaceDeformEnd,
    kDiskOutputBoundsMode,
    kDiskOutputPaddingX,
    kDiskOutputPaddingY,
    kDiskSurfaceCornerCurlStart,
    kDiskSurfaceCornerSelect,
    kDiskSurfaceCornerAmount,
    kDiskSurfaceCornerRadius,
    kDiskSurfaceCornerDirection,
    kDiskSurfaceCornerLength,
    kDiskSurfaceCornerCurlEnd,
    kDiskSurfaceEdgeTwistStart,
    kDiskSurfaceTwistEdge,
    kDiskSurfaceTwistAngle,
    kDiskSurfaceTwistFalloff,
    kDiskSurfaceEdgeTwistEnd,
    kDiskSurfaceRotationOriginStart,
    kDiskSurfaceRotationOriginMode,
    kDiskSurfaceRotationOriginX,
    kDiskSurfaceRotationOriginY,
    kDiskSurfaceRotationOriginEnd,
    kDiskSurfaceCorner2Amount,
    kDiskSurfaceCorner2Radius,
    kDiskSurfaceCorner2Direction,
    kDiskSurfaceCorner2Length,
    kDiskSurfaceCorner3Amount,
    kDiskSurfaceCorner3Radius,
    kDiskSurfaceCorner3Direction,
    kDiskSurfaceCorner3Length,
    kDiskSurfaceCorner4Amount,
    kDiskSurfaceCorner4Radius,
    kDiskSurfaceCorner4Direction,
    kDiskSurfaceCorner4Length,
    kDiskSurfaceTwist2Angle,
    kDiskSurfaceTwist2Falloff,
    kDiskSurfaceTwist3Angle,
    kDiskSurfaceTwist3Falloff,
    kDiskSurfaceTwist4Angle,
    kDiskSurfaceTwist4Falloff,
    kDiskSurfaceBackSourceSlot
};

extern "C" {

DllExport PF_Err EffectMain(
    PF_Cmd cmd,
    PF_InData* in_data,
    PF_OutData* out_data,
    PF_ParamDef* params[],
    PF_LayerDef* output,
    void* extra);

}
